# Generated by Django 6.0.4 on 2026-04-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imag',
            field=models.ImageField(blank=True, default='noImage.png', upload_to=''),
        ),
    ]
