# Generated by Django 6.0.4 on 2026-04-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imag',
            new_name='img',
        ),
    ]
